Repository lonkaars/crepe, pull requests merged in 2024-12, with the labels that each got.

#53 Jaro/collision system
  asset/texture/circle.png
  asset/texture/square.png
  src/crepe/Collider.cpp
  src/crepe/Collider.h
  src/crepe/api/BoxCollider.cpp
  src/crepe/api/BoxCollider.h
  src/crepe/api/CMakeLists.txt
  src/crepe/api/CircleCollider.cpp
  src/crepe/api/CircleCollider.h
  src/crepe/api/Event.h
  src/crepe/api/LoopManager.cpp
  src/crepe/api/Rigidbody.cpp
  src/crepe/api/Rigidbody.h
  src/crepe/api/Script.h
  src/crepe/system/CollisionSystem.cpp
  src/crepe/system/CollisionSystem.h
  src/crepe/system/PhysicsSystem.cpp
  src/example/CMakeLists.txt
  src/example/game.cpp
  src/test/CMakeLists.txt
  src/test/CollisionTest.cpp
  src/test/PhysicsTest.cpp
  src/test/Profiling.cpp
Labels: review me, high priority

#68 Max/ai
  mwe/events/include/event.h
  src/crepe/api/AI.cpp
  src/crepe/api/AI.h
  src/crepe/api/CMakeLists.txt
  src/crepe/api/LoopManager.cpp
  src/crepe/api/LoopManager.h
  src/crepe/api/Vector2.h
  src/crepe/api/Vector2.hpp
  src/crepe/manager/SaveManager.cpp
  src/crepe/manager/SaveManager.h
  src/crepe/system/AISystem.cpp
  src/crepe/system/AISystem.h
  src/crepe/system/AudioSystem.cpp
  src/crepe/system/CMakeLists.txt
  src/example/AITest.cpp
  src/example/CMakeLists.txt
  src/test/Vector2Test.cpp
Labels: fix me

#63 gameloop improvements + Singelton removal
  src/crepe/api/CMakeLists.txt
  src/crepe/api/IKeyListener.cpp
  src/crepe/api/IKeyListener.h
  src/crepe/api/IMouseListener.cpp
  src/crepe/api/IMouseListener.h
  src/crepe/api/LoopManager.cpp
  src/crepe/api/LoopManager.h
  src/crepe/api/LoopTimer.cpp
  src/crepe/api/LoopTimer.h
  src/crepe/facade/SDLContext.cpp
  src/crepe/manager/CMakeLists.txt
  src/crepe/manager/EventManager.cpp
  src/crepe/manager/EventManager.h
  src/crepe/manager/LoopTimerManager.cpp
  src/crepe/manager/LoopTimerManager.h
  src/crepe/manager/Mediator.h
  src/crepe/manager/SceneManager.cpp
  src/crepe/system/AISystem.cpp
  src/crepe/system/AnimatorSystem.cpp
  src/test/CMakeLists.txt
  src/test/CollisionTest.cpp
  src/test/EventTest.cpp
  src/test/InputTest.cpp
  src/test/LoopManagerTest.cpp
  src/test/LoopTimerTest.cpp
  src/test/ScriptTest.h
Labels: fix me

#71 pixel to game units for input system
  src/crepe/facade/SDLContext.cpp
  src/crepe/facade/SDLContext.h
  src/crepe/system/RenderSystem.cpp
  src/crepe/system/RenderSystem.h
  src/example/rendering_particle.cpp
  src/test/Profiling.cpp
Labels: fix me

#64 Jaro/physics system improvement
  src/crepe/api/Config.h
  src/crepe/api/Rigidbody.h
  src/crepe/system/AISystem.cpp
  src/crepe/system/PhysicsSystem.cpp
  src/example/AITest.cpp
  src/example/game.cpp
  src/test/PhysicsTest.cpp
Labels: fix me

#76 fps hotfix + regression test
  src/crepe/manager/LoopTimerManager.cpp
  src/crepe/manager/LoopTimerManager.h
  src/test/LoopTimerTest.cpp
Labels: review me

#81 Jaro/collision system
  src/crepe/system/CollisionSystem.cpp
  src/example/game.cpp
Labels: review me, high priority

#74 Jaro/particle system improvement
  src/crepe/Particle.cpp
  src/crepe/Particle.h
  src/crepe/api/LoopManager.cpp
  src/crepe/api/ParticleEmitter.cpp
  src/crepe/api/ParticleEmitter.h
  src/crepe/system/ParticleSystem.cpp
  src/crepe/system/ParticleSystem.h
  src/crepe/system/RenderSystem.cpp
  src/example/game.cpp
  src/example/rendering_particle.cpp
  src/test/ParticleTest.cpp
  src/test/Profiling.cpp
Labels: high priority, fix me

#69 keyboard state + window events + click_tolerance button
  src/crepe/api/Button.cpp
  src/crepe/api/Button.h
  src/crepe/api/Config.h
  src/crepe/api/Event.h
  src/crepe/api/KeyCodes.h
  src/crepe/api/Script.cpp
  src/crepe/api/Script.h
  src/crepe/facade/EventData.h
  src/crepe/facade/SDLContext.cpp
  src/crepe/facade/SDLContext.h
  src/crepe/system/InputSystem.cpp
  src/crepe/system/InputSystem.h
  src/example/button.cpp
  src/test/EventTest.cpp
  src/test/InputTest.cpp
Labels: review me

#89 fix audio segfault
  src/crepe/api/LoopManager.h
Labels: review me, high priority

#87 Wouter/button improvement
  src/crepe/api/Button.cpp
  src/crepe/api/Button.h
  src/crepe/api/Event.h
  src/crepe/system/InputSystem.cpp
  src/crepe/system/InputSystem.h
  src/test/InputTest.cpp
Labels: review me

#85 Jaro/collision system handeling
  src/crepe/api/Rigidbody.h
  src/crepe/api/Vector2.h
  src/crepe/api/Vector2.hpp
  src/crepe/facade/SDLContext.cpp
  src/crepe/system/CollisionSystem.cpp
  src/crepe/system/CollisionSystem.h
  src/crepe/system/ParticleSystem.cpp
  src/crepe/system/RenderSystem.cpp
  src/crepe/util/AbsolutePosition.h
  src/example/game.cpp
  src/test/CollisionTest.cpp
  src/test/Profiling.cpp
Labels: fix me
